apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveryservice
  template:
    metadata:
      labels:
        app: deliveryservice
    spec:
      containers:
        - name: deliveryservice
          image: deliveryservice
          imagePullPolicy: Never
          ports:
            - containerPort: 8030
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8030"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: KAFKA_CLUSTERS_0_NAME
              value: "kafka"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka:9092"
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: "zookeeper:2181"
